version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    command: npm start -- --disable-host-check
  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf