version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
  backend:
    build:
      context: ./backend
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    # volumes:
    # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
