version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
  backend:
    build:
      context: ./backend
  analysis:
    build:
      context: ./analysis
    ports:
      - "9000:9000"
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - analysis
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx